#!/bin/bash
#
#AUTHOR: TOUSSI MANOEL MALAURY
#DESCRIPTION
#
#COMMANDS

#color of output
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m' #No Color


POSTGRESQL_HOME=/usr/local/pgsql/
POSTGRESQL_LOG=/var/my_config/logs/postgresql/postgresql
POSTGRESQL_PID=/usr/local/pgsql/data/postmaster.pid
POSTGRESQL_DATA=$POSTGRESQL_HOME/data

start() {
    if [ -e $POSTGRESQL_PID ] 
    then
        echo -e "${yellow}PostgreSQL is already started ${NC}"
    else
        $POSTGRESQL_HOME/bin/pg_ctl -D $POSTGRESQL_DATA -l $POSTGRESQL_LOG start
    fi
}

stop() {
    if [ -e $POSTGRESQL_PID ]
    then
        $POSTGRESQL_HOME/bin/pg_ctl -D $POSTGRESQL_DATA -l $POSTGRESQL_LOG stop
        echo -e "${red}PostgreSQL is stopped"
    else
        echo -e "${yellow}PostgreSQL has already stopped ${NC}"
    fi
}

restart() {
    if [ -e $POSTGRESQL_PID ]
    then
        $POSTGRESQL_HOME/bin/pg_ctl -D $POSTGRESQL_DATA -l $POSTGRESQL_LOG reload
        echo -e "${yellow}PostgreSQL has restarted ${NC}"
    else
        $POSTGRESQL_HOME/bin/pg_ctl -D $POSTGRESQL_DATA -l $POSTGRESQL_LOG start
    fi
}

status() {
    if [ -e $POSTGRESQL_PID ]
    then
        $POSTGRESQL_HOME/bin/pg_ctl -D $POSTGRESQL_DATA status
        echo -e "${green}PostgreSQL is running ... ${NC}"
    else
        $POSTGRESQL_HOME/bin/pg_ctl -D $POSTGRESQL_DATA status
        echo -e "${red}PostgreSQL is stopped ${NC}"
    fi
}

list_databases() {
    $POSTGRESQL_HOME/bin/psql -U manoel -l 
}

connect() {
    list_databases
    echo -e "Connect to Database"
    read -p "Name of Database: " database
    $POSTGRESQL_HOME/bin/psql -W -U manoel -h localhost -d $database 
}

help()
{
   # Display Help
   echo "Available options are: "
   echo "{start|stop|restart|status|list_db|connect}"
   echo " "
   echo "start      to start PostgreSQL"
   echo "stop       to stop PostgreSQL"
   echo "restart    to restart PostgreSQL"
   echo "status     to look the status of PostgreSQL"
   echo "list_db    to list all databases"
   echo "connect    to connect to database"

}

case "$1" in 
"start")
start
;;

"stop")
stop
;;

"restart")
restart
;;

"status")
status
;;

"list_db")
list_databases
;;

"connect")
connect
;;

"")
start
;;

"-h")
help
;;

*)
help
;;

esac