#!/bin/bash
#AUTHOR: TOUSSI MANOEL MALAURY
#
#Description: start, stop, check status of elasticsearch 
###########################################################
#color of output
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[1;33m'
NC='\035[0m' #No Color
###########################################################
###########################################################
###########################################################
#these lines permit to check the status of MySQL service
ps -aux | grep "mysql" | pidof mysqld > /dev/null
verifier=$?
zero=0
###########################################################
#update variables below in according to your context or 
#set MYSQL_HOME as environment variable
##########################################################
MYSQL_HOME=$MYSQL_HOME
MYSQL_SCRIPTS=$MYSQL_HOME/support-files
########################################################
#get pid of MySQL
mysql_pid() {
    echo `ps -aux | grep "mysql" | pidof mysqld`
}
###############################################
start(){
	#check if MySQL service is running
    	if [ $zero != $verifier ]
    	then
		$MYSQL_SCRIPTS/mysql.server start
	else
		echo -e "${yellow}MySQL is already started ${NC}"
	fi
}

stop(){
	#check if MySQL is running
    	if [ $zero = $verifier ]
    	then
		$MYSQL_SCRIPTS/mysql.server stop
	else
		echo -e "${yellow}MySQL is already stopped ${NC}"
	fi
}

status(){
	$MYSQL_SCRIPTS/mysql.server status
}

reload(){
	$MYSQL_SCRIPTS/mysql.server reload
}

#to connect to  mysql shell
connect(){
	#check if MYSQL service is running
        if [ $zero = $verifier ]
	then
		read -p "user(default: root) : " user
		if [ $user ]
		then
			$MYSQL_HOME/bin/mysql -u $user -p
		else
			$MYSQL_HOME/bin/mysql -u root -p
		fi
	else
		echo -e "${red}MySQL is stopped. ${NC}"
		echo -e "${red}You need to start MySQL service ${NC}"
	fi
}

#Display Help
help()
{
   echo "Available options are: "
   echo "{start|stop|restart|status|connect|-h|help}"
   echo " "
   echo "start      to start MYSQL"
   echo "stop       to stop MySQL"
   echo "restart    to restart MySQL"
   echo "status     to check the status of MySQL"
   echo "connect    to log on the command line"
   echo "help or -h	    to display help"
}

case "$1" in
	#start MySQL
	"start")
		start
	;;
	"")
		start
	;;
	#stop MySQL
	"stop")
		stop
	;;
	#restart MySQL
	"restart")
		reload
	;;
	#check status of MySQL
	"status")
		status
	;;
	#connect on MYSQL shell
	"connect")
		connect
	;;
	#display help
	"")
		help
	;;
	"-h")
		help
	;;
	*)
		help
	;;
esac
