#!/bin/bash
#!/bin/bash
#
#AUTHOR: TOUSSI MANOEL MALAURY
#DESCRIPTION
#
#COMMANDS

###########################################################
#these lines permit to check the status of MySQL service
ps -aux | grep "mysql" | pidof mysqld > /dev/null
verifier=$?
zero=0
###########################################################

###########################################################
#color of output
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m' #No Color
###########################################################

MYSQL_HOME=/usr/local/mysql
MYSQL_PID=$MYSQL_HOME/data/mysql.pid

#get the pid of MySQL
mysql_pid() {
    echo `ps -aux | grep "mysql" | pidof mysqld`
}

#to start MySQL service
start() {
    #check if MySQL service is running
    if [ $zero != $verifier ]
    then
        #check if mysql.pid exists
        if [ -e $MYSQL_PID ]
        then
        rm $MYSQL_PID
        $MYSQL_HOME/bin/mysqld -D --pid-file=$MYSQL_PID
        echo -e "${yellow}MySQL is starting ... ${NC}"
        else
        $MYSQL_HOME/bin/mysqld -D --pid-file=$MYSQL_PID
        echo -e "${yellow}MySQL is starting ... ${NC}"
        fi
    else
    echo -e "${yellow}MySQL is already started ${NC}"
    fi
}

#to stop MySQL service
stop() {
    #check if MySQL is running
    if [ $zero = $verifier ]
    then
        #check if mysql.pid exists
        if [ -e $MYSQL_PID ]
        then
        pkill -F $MYSQL_PID
        echo -e "${red}MySQL is stopped ${NC}"
        else
        pid=${mysql_pid}
        kill -9 $pid
        echo -e "${red}MySQL is stopped ${NC}"
        fi 
    else
    echo -e "${yellow}MySQL has already stopped ${NC}"
    fi
}

#check the status of MySQL
status() {
    #check if MySQL is running
    if [ $zero = $verifier ]
    then
    echo -e "${green}MySQL is running ... ${NC}"
    else
    echo -e "${red}MySQL is stopped ${NC}"
    fi
}

#to log on the command line
connect() {
    #check if MySQL is running
    if [ $zero = $verifier ]
    then
        read -p "user(default: root) : " user
        #check if user is not empty
        if [ $user ]
        then
            $MYSQL_HOME/bin/mysql -u $user -p
        else
            $MYSQL_HOME/bin/mysql -u root -p
        fi
    else
        echo -e "${red}MySQL is stopped ${NC}"
        echo -e "${yellow}You need to start MySQL service ${NC}"
    fi
}

#Display Help
help() {
    echo "Available options are: "
    echo "{start|stop|status|log}"
    echo " "
    echo "start     to start MySQL"
    echo "stop      to stop MySQL"
    echo "status    to check the status of MySQL"
    echo "connect   to log on the command line"

}

case "$1" in 
"start")
start
;;

"stop")
stop
;;

"status")
status
;;

"connect")
connect
;;

"")
start
;;

"-h")
help
;;

*)
help
;;

esac
